# Generated by Django 4.0.10 on 2025-05-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futurex_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('submitted', 'Submitted')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futurex_ecommerce.productsku'),
        ),
    ]
