# Generated by Django 4.0.10 on 2025-05-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futurex_ecommerce', '0002_alter_cart_state_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_sku',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_sku')},
        ),
    ]
