# Generated by Django 5.2.1 on 2025-06-03 10:08

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('org', models.CharField(db_collation='NOCASE', max_length=255)),
                ('catalog_visibility', models.TextField(null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('display_name', models.TextField(null=True)),
                ('enrollment_start', models.DateTimeField(null=True)),
                ('enrollment_end', models.DateTimeField(null=True)),
                ('self_paced', models.BooleanField(default=False)),
                ('course_image_url', models.TextField()),
                ('visible_to_staff_only', models.BooleanField(default=False)),
                ('effort', models.TextField(null=True)),
            ],
            options={
                'db_table': 'course_overviews_courseoverview',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(default='audit', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_models.courseoverview')),
            ],
            options={
                'db_table': 'student_courseenrollment',
            },
        ),
        migrations.CreateModel(
            name='CourseMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_slug', models.CharField(max_length=100, verbose_name='Mode')),
                ('mode_display_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('min_price', models.IntegerField(default=0, verbose_name='Price')),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('_expiration_datetime', models.DateTimeField(blank=True, db_column='expiration_datetime', default=None, null=True, verbose_name='Upgrade Deadline')),
                ('expiration_datetime_is_explicit', models.BooleanField(default=False, verbose_name='Lock upgrade deadline date')),
                ('sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modes', to='fake_models.courseoverview')),
            ],
            options={
                'db_table': 'course_modes_coursemode',
                'unique_together': {('course', 'mode_slug', 'currency')},
            },
        ),
    ]
